/**
 * @file error_codes.h
 * @brief Error code definitions for NexusLink SemVerX
 */

#ifndef NLINK_SEMVERX_CORE_ERROR_CODES_H
#define NLINK_SEMVERX_CORE_ERROR_CODES_H

// Configuration result codes
typedef enum {
    NLINK_CONFIG_SUCCESS = 0,
    NLINK_CONFIG_ERROR_FILE_NOT_FOUND = -1,
    NLINK_CONFIG_ERROR_PARSE_FAILED = -2,
    NLINK_CONFIG_ERROR_INVALID_FORMAT = -3,
    NLINK_CONFIG_ERROR_MISSING_REQUIRED_FIELD = -4,
    NLINK_CONFIG_ERROR_THREAD_POOL_INVALID = -5,
    NLINK_CONFIG_ERROR_MEMORY_ALLOCATION = -6,
    NLINK_CONFIG_ERROR_RANGE_STATE_INVALID = -7
} nlink_config_result_t;

// CLI result codes
typedef enum {
    NLINK_CLI_SUCCESS = 0,
    NLINK_CLI_ERROR_INVALID_ARGUMENTS = -1,
    NLINK_CLI_ERROR_CONFIG_NOT_FOUND = -2,
    NLINK_CLI_ERROR_PARSE_FAILED = -3,
    NLINK_CLI_ERROR_VALIDATION_FAILED = -4,
    NLINK_CLI_ERROR_THREADING_INVALID = -5,
    NLINK_CLI_ERROR_COMPONENT_DISCOVERY_FAILED = -6,
    NLINK_CLI_ERROR_INTERNAL_ERROR = -7
} nlink_cli_result_t;

#endif /* NLINK_SEMVERX_CORE_ERROR_CODES_H */
